#!/bin/bash -x

proj_list="/var/FLH-Web"

for proj in ${proj_list}
do
    if [ -d ${proj} ]; then
        cd ${proj}
        git checkout -f && git clean -fx -d && git checkout master && git pull origin master
        cd -
    fi
done

sudo /sbin/shutdown -r 3

