#!/bin/bash -x

proj_list="/var/FLH-Web"
git_branch=$(git rev-parse --abbrev-ref HEAD)

for proj in ${proj_list}
do
    if [ -d ${proj} ]; then
        cd ${proj}
        git checkout -f && git clean -fx -d && git checkout ${git_branch} && git pull origin ${git_branch}
        cd -
    fi
done

sudo cp /var/FLH-Web/config/crontab_root /var/spool/cron/crontabs/root
sudo chown root:crontab /var/spool/cron/crontabs/root
sudo service cron restart

sudo /sbin/shutdown -r 3

