#!/bin/bash -x

proj_list="/var/FLH-Web"

for proj in ${proj_list}
do
    if [ -d ${proj} ]; then
        cd ${proj}
        git checkout -f && git clean -fx -d && git checkout rel_ct && git pull origin rel_ct
        cd -
    fi
done

sudo cp /var/FLH-Web/config/crontab_root /var/spool/cron/crontabs/root
sudo chown root:crontab /var/spool/cron/crontabs/root
sudo service cron restart

sudo /sbin/shutdown -r 3

